name: comfyshare
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.23
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^4.0.4
  gap: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.1
  provider: ^6.1.1
  markdown: ^7.1.1
  flutter_markdown: ^0.6.15
  http: ^0.13.6
  download: ^1.0.0
  dio: ^5.4.0
  url_launcher: ^6.1.11
  file_picker: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/ComfyLogo.png
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/DuckyLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/DuckyLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/DuckyLogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/DuckyLogo.png"